# Generated by Django 5.2.17 on 2026-08-26 16:03

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colis', '0001_initial'),
        ('geo', '0002_initial'),
        ('iam', '0001_initial'),
        ('voyage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=20, verbose_name='N° facture')),
                ('customer_id', models.UUIDField(blank=True, null=True, verbose_name='ID client')),
                ('customer_type', models.CharField(blank=True, max_length=20, verbose_name='Type de client')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom client')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('subtotal_xof', models.IntegerField(verbose_name='Sous-total (XOF)')),
                ('tax_xof', models.IntegerField(default=0, verbose_name='Taxes (XOF)')),
                ('total_xof', models.IntegerField(verbose_name='Total (XOF)')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payée à')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'billing_invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('reference_type', models.CharField(blank=True, max_length=20, verbose_name='Type de référence')),
                ('reference_id', models.UUIDField(blank=True, null=True, verbose_name='ID de référence')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('unit_price_xof', models.IntegerField(verbose_name='Prix unitaire (XOF)')),
                ('amount_xof', models.IntegerField(verbose_name='Montant (XOF)')),
                ('tax_xof', models.IntegerField(default=0, verbose_name='Taxes (XOF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée à')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'db_table': 'billing_invoice_lines',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('mtn_momo', 'MTN Mobile Money'), ('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire')], max_length=20, verbose_name='Provider')),
                ('provider_tx_id', models.CharField(blank=True, max_length=100, verbose_name='ID transaction provider')),
                ('amount_xof', models.IntegerField(verbose_name='Montant (XOF)')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='initiated', max_length=20, verbose_name='Statut')),
                ('failure_reason', models.CharField(blank=True, max_length=300, verbose_name="Motif d'échec")),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Réponse provider')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='Initié à')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='colis.order')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='voyage.reservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'billing_payments',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('type', models.CharField(choices=[('voyage', 'Voyage'), ('colis', 'Colis')], max_length=20, verbose_name='Type')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valide à partir de')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'à")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Grille tarifaire',
                'verbose_name_plural': 'Grilles tarifaires',
                'db_table': 'billing_price_lists',
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Forfait'), ('per_km', 'Par km'), ('per_kg', 'Par kg'), ('per_zone', 'Par zone')], default='fixed', max_length=20, verbose_name='Méthode de calcul')),
                ('base_amount_xof', models.IntegerField(verbose_name='Montant de base (XOF)')),
                ('rate_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taux par unité')),
                ('min_amount_xof', models.IntegerField(blank=True, null=True, verbose_name='Montant minimum (XOF)')),
                ('max_amount_xof', models.IntegerField(blank=True, null=True, verbose_name='Montant maximum (XOF)')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='Conditions')),
                ('destination_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rules_dest', to='geo.zone')),
                ('origin_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rules_origin', to='geo.zone')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='billing.pricelist')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rules', to='voyage.route')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Règle tarifaire',
                'verbose_name_plural': 'Règles tarifaires',
                'db_table': 'billing_price_rules',
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'invoice_number'), name='unique_invoice_number_per_tenant'),
        ),
    ]
