# Generated by Django 5.2.17 on 2026-09-07 14:45

"""Documente la convention `customer_id` / `customer_type` sur la facture.

Aucun changement de schéma : seuls les `help_text` évoluent, mais Django les
suit, d'où cette migration. Le couple reste une référence polymorphe sans clé
étrangère — voir les constantes `CUSTOMER_TYPE_*` dans billing/models.py.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_id',
            field=models.UUIDField(blank=True, help_text="Interprété selon customer_type : 'client_user' désigne un iam.User de rôle client, 'external' un client non inscrit.", null=True, verbose_name='ID client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_type',
            field=models.CharField(blank=True, help_text="'client_user' | 'external' | vide (factures antérieures à la convention).", max_length=20, verbose_name='Type de client'),
        ),
    ]
