# Generated by Django 5.2.17 on 2026-10-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_customer_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_id',
            field=models.UUIDField(blank=True, help_text="Interprété selon customer_type : 'client_user' désigne un iam.User de rôle client, 'passenger' une fiche voyage.Passenger du tenant, 'external' un client non inscrit sans identifiant exploitable (customer_id reste alors nul).", null=True, verbose_name='ID client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_type',
            field=models.CharField(blank=True, help_text="'client_user' (compte TOUPAC inscrit) | 'passenger' (voyageur sans compte, identifié par sa fiche Passenger du tenant) | 'external' (client non inscrit, entreprise ou administration) | vide (factures antérieures à la convention).", max_length=20, verbose_name='Type de client'),
        ),
    ]
