# Generated by Django 5.2.17 on 2026-09-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='customer_user',
            field=models.ForeignKey(blank=True, help_text="Compte client global rattaché à ce passager. Facultatif : on voyage souvent pour quelqu'un d'autre — un parent, un collègue — qui n'a pas de compte. Ce passager reste alors un invité.", limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_records', to=settings.AUTH_USER_MODEL, verbose_name='Compte client TOUPAC'),
        ),
    ]
