# Generated by Django 5.2.17 on 2026-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_passenger_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlevent',
            name='rejection_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code de rejet'),
        ),
    ]
