# Generated by Django 5.2.17 on 2026-10-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0014_driver_not_staff'),
        ('voyage', '0003_controlevent_rejection_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatmap',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Plan système réutilisable par tous les tenants. Non éditable, non supprimable par les tenants ; clonable pour créer une copie.', verbose_name='Template système'),
        ),
        migrations.AlterField(
            model_name='seatmap',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_seatmap_set', to='iam.tenant'),
        ),
    ]
