# Generated by Django 5.2.17 on 2026-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_seed_system_seat_map_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='arrival_offset_minutes',
            field=models.PositiveIntegerField(default=0, help_text="Minutes depuis le départ pour l'arrivée à cette escale.", verbose_name='Offset arrivée (minutes)'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='departure_offset_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes depuis le départ pour le départ de cette escale. Égal à `arrival_offset_minutes` si pas de pause.', verbose_name='Offset départ (minutes)'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='offset_minutes',
            field=models.PositiveIntegerField(default=0, help_text='DEPRECATED : utiliser arrival_offset_minutes / departure_offset_minutes. Conservé pour compatibilité app RN mobile. Reflète departure_offset_minutes à chaque save.', verbose_name='Décalage (minutes)'),
        ),
    ]
