# Generated by Django 5.2.17 on 2026-09-05 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredential',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
