# Generated by Django 5.2.17 on 2026-09-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_alter_apicredential_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin TOUPAC'), ('admin', 'Admin compagnie'), ('dispatcher', 'Dispatcher'), ('agent', 'Agent de guichet'), ('driver', 'Chauffeur'), ('controller', 'Contrôleur'), ('client', 'Client'), ('service_account', 'Compte de service')], default='agent', max_length=20, verbose_name='Rôle'),
        ),
    ]
