# Generated by Django 5.2.17 on 2026-09-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_backfill_service_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text="Dict de catégories opt-in/opt-out. Ex: {'marketing': False, 'trip_updates': True}. Clé absente = opt-in ; les catégories de notifications.preferences.NEVER_OPT_OUT ignorent la valeur.", verbose_name='Préférences de notification'),
        ),
    ]
