# Generated by Django 5.2.17 on 2026-09-06 19:13

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_add_notification_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex : « Chatbot Toupac BI production »', max_length=100, verbose_name='Nom')),
                ('platform_service', models.CharField(help_text='Slug déclaré dans iam/platform_services.py (ex : chatbot-bi).', max_length=50, verbose_name='Service plateforme')),
                ('key_prefix', models.CharField(db_index=True, max_length=24, unique=True, verbose_name='Préfixe clé')),
                ('key_hash', models.CharField(max_length=200, verbose_name='Hash clé')),
                ('platform_scopes', models.JSONField(blank=True, default=list, verbose_name='Scopes plateforme')),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='Liste de CIDR autorisés, ex : ["52.34.10.5/32", "10.0.0.0/24"]. Liste vide = accepté uniquement en DEBUG.', verbose_name='IP autorisées (CIDR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('expires_at', models.DateTimeField(help_text='Rotation forcée. Défaut à la création : +90 jours.', verbose_name='Expire le')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier usage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_credentials_issued', to=settings.AUTH_USER_MODEL, verbose_name='Émise par')),
            ],
            options={
                'verbose_name': 'Clé plateforme',
                'verbose_name_plural': 'Clés plateforme',
                'db_table': 'iam_platform_credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=200, verbose_name='Endpoint')),
                ('method', models.CharField(max_length=10, verbose_name='Méthode')),
                ('ip', models.GenericIPAddressField(verbose_name='IP source')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('status_code', models.IntegerField(verbose_name='Code HTTP')),
                ('latency_ms', models.IntegerField(blank=True, null=True, verbose_name='Latence (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant_context', models.ForeignKey(blank=True, help_text='Tenant résolu depuis X-Tenant-ID. Vide pour les endpoints globaux.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_logs', to='iam.tenant', verbose_name='Tenant visé')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='iam.platformcredential', verbose_name='Clé')),
            ],
            options={
                'verbose_name': 'Appel plateforme',
                'verbose_name_plural': 'Appels plateforme',
                'db_table': 'iam_platform_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['credential', '-created_at'], name='iam_platfor_credent_e19c7d_idx'), models.Index(fields=['tenant_context', '-created_at'], name='iam_platfor_tenant__64c27d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_service', models.CharField(max_length=50, verbose_name='Service plateforme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Accordé le')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Révoqué le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Accordé par')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_subscriptions', to='iam.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Abonnement plateforme',
                'verbose_name_plural': 'Abonnements plateforme',
                'db_table': 'iam_tenant_subscriptions',
                'ordering': ['tenant__name', 'platform_service'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'platform_service'), name='unique_tenant_service_subscription')],
            },
        ),
    ]
