# Generated by Django 5.2.17 on 2026-08-26 03:05

import core.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_initial'),
        ('geo', '0002_initial'),
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.CharField(max_length=20, verbose_name='Identifiant interne')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Nom client')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone client')),
                ('pickup_window_start', models.DateTimeField(blank=True, null=True, verbose_name='Fenêtre enlèvement — début')),
                ('pickup_window_end', models.DateTimeField(blank=True, null=True, verbose_name='Fenêtre enlèvement — fin')),
                ('delivery_window_start', models.DateTimeField(blank=True, null=True, verbose_name='Fenêtre livraison — début')),
                ('delivery_window_end', models.DateTimeField(blank=True, null=True, verbose_name='Fenêtre livraison — fin')),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('urgent', 'Urgent')], default='standard', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmée'), ('dispatched', 'Dispatchée'), ('picked_up', 'Enlevée'), ('in_transit', 'En transit'), ('delivered', 'Livrée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('total_amount_xof', models.IntegerField(blank=True, null=True, verbose_name='Montant total (XOF)')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut paiement')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('dropoff_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_orders', to='geo.place', verbose_name='Lieu de livraison')),
                ('pickup_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_orders', to='geo.place', verbose_name="Lieu d'enlèvement")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'colis_orders',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pickup', 'Enlèvement'), ('delivery', 'Livraison')], max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Assignée'), ('accepted', 'Acceptée'), ('en_route', 'En route'), ('arrived', 'Arrivée'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20, verbose_name='Statut')),
                ('sequence_order', models.IntegerField(blank=True, null=True, verbose_name='Ordre de tournée')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Arrivée estimée')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Arrivée réelle')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminée à')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name="Motif d'échec")),
                ('route_geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326, verbose_name='Géométrie trajet')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tasks', to='fleet.driver')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_tasks', to='geo.place')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tasks', to='fleet.vehicle')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tasks', to='colis.order')),
            ],
            options={
                'verbose_name': 'Tâche de livraison',
                'verbose_name_plural': 'Tâches de livraison',
                'db_table': 'colis_delivery_tasks',
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=20, verbose_name='N° de suivi')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Poids (kg)')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Longueur (cm)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Largeur (cm)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Hauteur (cm)')),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('fragile', 'Fragile'), ('perishable', 'Périssable'), ('hazardous', 'Dangereux')], default='standard', max_length=20, verbose_name='Catégorie')),
                ('declared_value_xof', models.IntegerField(blank=True, null=True, verbose_name='Valeur déclarée (XOF)')),
                ('status', models.CharField(choices=[('created', 'Créé'), ('picked_up', 'Enlevé'), ('in_transit', 'En transit'), ('at_hub', 'Au hub'), ('out_for_delivery', 'En cours de livraison'), ('delivered', 'Livré'), ('returned', 'Retourné')], default='created', max_length=20, verbose_name='Statut')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='colis.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
                'db_table': 'colis_parcels',
            },
        ),
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('signature', 'Signature'), ('photo', 'Photo'), ('qr_scan', 'Scan QR'), ('otp', 'Code OTP')], max_length=20, verbose_name='Type')),
                ('signature_url', models.URLField(blank=True, max_length=500, verbose_name='Signature')),
                ('photos_urls', models.JSONField(blank=True, default=list, verbose_name='Photos')),
                ('otp_code', models.CharField(blank=True, max_length=10, verbose_name='Code OTP')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='Nom destinataire')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone destinataire')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('gps_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Position GPS')),
                ('delivery_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='colis.deliverytask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Preuve de livraison',
                'verbose_name_plural': 'Preuves de livraison',
                'db_table': 'colis_proofs_of_delivery',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'status'], name='colis_order_tenant__1ffcc5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'internal_id'], name='colis_order_tenant__f3187b_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('tenant', 'internal_id'), name='unique_order_internal_id_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['tenant', 'status'], name='colis_deliv_tenant__eedb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['tenant', 'driver'], name='colis_deliv_tenant__24b371_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcel',
            constraint=models.UniqueConstraint(fields=('tracking_number',), name='unique_parcel_tracking_number'),
        ),
    ]
