# Generated by Django 5.2.17 on 2026-09-01 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0001_initial'),
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trip',
            field=models.ForeignKey(blank=True, help_text="Si le colis voyage en soute d'un bus passagers", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_orders', to='voyage.trip', verbose_name='Voyage associé'),
        ),
    ]
