# Generated by Django 5.2.17 on 2026-09-08 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0003_order_customer_clean'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom destinataire'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone destinataire'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_orders', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire (compte client)'),
        ),
    ]
