# Generated by Django 5.2.17 on 2026-08-25 02:22

import core.models
import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='N° permis')),
                ('license_class', models.CharField(blank=True, max_length=10, verbose_name='Catégorie permis')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='Expiration permis')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('on_trip', 'En voyage'), ('off_duty', 'Hors service')], default='available', max_length=20, verbose_name='Statut')),
                ('score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Score')),
                ('last_known_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Dernière position')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
                'db_table': 'fleet_drivers',
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('zone', models.CharField(blank=True, max_length=100, verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Flotte',
                'verbose_name_plural': 'Flottes',
                'db_table': 'fleet_fleets',
            },
        ),
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fleet_fleet_vehicles',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20, verbose_name='Immatriculation')),
                ('make', models.CharField(blank=True, max_length=50, verbose_name='Marque')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='Modèle')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='N° châssis')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En service'), ('maintenance', 'Maintenance'), ('decommissioned', 'Déclassé')], default='available', max_length=20, verbose_name='Statut')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Position')),
                ('traccar_device_id', models.CharField(blank=True, max_length=50, verbose_name='ID Traccar')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'db_table': 'fleet_vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('insurance', 'Assurance'), ('registration', 'Carte grise'), ('inspection', 'Visite technique'), ('transport_permit', 'Autorisation de transport')], max_length=30, verbose_name='Type')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='N° document')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Date émission')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Date expiration')),
                ('file_url', models.URLField(blank=True, max_length=500, verbose_name='Fichier')),
                ('status', models.CharField(default='valid', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Document véhicule',
                'verbose_name_plural': 'Documents véhicules',
                'db_table': 'fleet_vehicle_documents',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('default_capacity', models.PositiveIntegerField(verbose_name='Capacité par défaut')),
                ('fuel_type', models.CharField(blank=True, max_length=20, verbose_name='Carburant')),
            ],
            options={
                'verbose_name': 'Type de véhicule',
                'verbose_name_plural': 'Types de véhicules',
                'db_table': 'fleet_vehicle_types',
            },
        ),
    ]
