# Generated by Django 5.2.17 on 2026-08-25 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fleet',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_fleets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fleet',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant'),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.fleet'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant'),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='vehicles',
            field=models.ManyToManyField(related_name='fleets', through='fleet.FleetVehicle', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet.vehicletype'),
        ),
        migrations.AlterUniqueTogether(
            name='fleetvehicle',
            unique_together={('fleet', 'vehicle')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicletype',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['tenant', 'status'], name='fleet_vehic_tenant__0b9fc1_idx'),
        ),
    ]
