# Generated by Django 5.2.17 on 2026-10-05 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_initial'),
        ('voyage', '0003_controlevent_rejection_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='default_seat_map',
            field=models.ForeignKey(blank=True, help_text="Plan utilisé par défaut lors de la création d'un voyage avec ce véhicule. Peut être overridé au moment de la création.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_default', to='voyage.seatmap', verbose_name='Plan de sièges par défaut'),
        ),
    ]
