# Generated by Django 5.2.18 on 2026-10-10 19:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_license_classes(apps, schema_editor):
    """Pour chaque Driver existant, remplit license_classes à partir du
    scalaire legacy license_class : [license_class] si non vide, [] sinon."""
    Driver = apps.get_model("fleet", "Driver")
    for driver in Driver.objects.all().iterator():
        if driver.license_class:
            driver.license_classes = [driver.license_class]
        else:
            driver.license_classes = []
        driver.save(update_fields=["license_classes"])


def noop(apps, schema_editor):
    """Reverse : rien à défaire (le champ sera droppé par la reverse de AddField)."""


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_default_seat_map'),
        ('iam', '0014_driver_not_staff'),
        ('voyage', '0008_seatmap_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='driver',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='driver',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact urgence (nom)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact urgence (tél.)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), blank=True, default=list, size=None, verbose_name='Catégories permis'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_issued',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'obtention du permis"),
        ),
        migrations.AddField(
            model_name='driver',
            name='matricule',
            field=models.CharField(blank=True, max_length=16, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='driver',
            name='medical_check_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Visite médicale (expiration)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='code',
            field=models.CharField(blank=True, max_length=16, verbose_name='Code interne'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° moteur'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('essence', 'Essence'), ('gasoil', 'Gasoil'), ('hybride', 'Hybride')], default='diesel', max_length=20, verbose_name='Carburant'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_service_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Dernière révision (km)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Prochaine révision'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Odomètre (km)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_interval_km',
            field=models.PositiveIntegerField(default=20000, verbose_name='Intervalle révision (km)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=20, verbose_name='Boîte'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='category',
            field=models.CharField(choices=[('interurbain', 'Interurbain'), ('urbain', 'Urbain'), ('utilitaire', 'Utilitaire')], default='interurbain', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='default_luggage_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.luggagepolicy', verbose_name='Politique bagages par défaut'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hauteur (m)'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='hold_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Soute (m³)'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Longueur (m)'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='permit_required',
            field=models.CharField(choices=[('B', 'B'), ('C', 'C'), ('D', 'D'), ('D1', 'D1'), ('BE', 'BE')], default='D', max_length=4, verbose_name='Permis requis'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='ptac_kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PTAC (kg)'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='short',
            field=models.CharField(blank=True, max_length=16, verbose_name='Nom court'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Largeur (m)'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='type',
            field=models.CharField(choices=[('insurance', 'Assurance'), ('registration', 'Carte grise'), ('inspection', 'Visite technique'), ('transport_permit', 'Autorisation de transport'), ('cedeao_green_card', 'Carte verte CEDEAO'), ('patente', 'Patente')], max_length=30, verbose_name='Type'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('matricule', ''), _negated=True), fields=('tenant', 'matricule'), name='unique_driver_matricule_per_tenant'),
        ),
        migrations.RunPython(backfill_license_classes, reverse_code=noop),
    ]
