# Generated by Django 5.2.18 on 2026-10-10 21:48

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_fleet_enrich'),
        ('iam', '0014_driver_not_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='fleet.driver', verbose_name='Chauffeur affecté'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/documents/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Fichier (URL)'),
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateField(verbose_name="Date d'intervention")),
                ('type', models.CharField(choices=[('oil_change', 'Vidange'), ('tires', 'Pneus'), ('technical_visit', 'Visite technique'), ('breakdown', 'Panne'), ('major_service', 'Révision complète'), ('other', 'Autre')], max_length=32, verbose_name='Type')),
                ('odometer_km', models.PositiveIntegerField(verbose_name='Odomètre (km)')),
                ('shop', models.CharField(blank=True, max_length=100, verbose_name='Garage / prestataire')),
                ('cost_xof', models.PositiveIntegerField(blank=True, null=True, verbose_name='Coût (XOF)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance véhicule',
                'verbose_name_plural': 'Maintenances véhicules',
                'db_table': 'fleet_vehicle_maintenances',
                'ordering': ['-at', '-created_at'],
            },
        ),
    ]
