# Generated by Django 5.2.18 on 2026-10-10 21:59

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_vehicle_maintenance_and_assigned_driver'),
        ('iam', '0014_driver_not_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('license_scan', 'Permis scanné'), ('medical_check', 'Visite médicale'), ('contract', 'Contrat de travail'), ('training_cert', 'Attestation de formation'), ('criminal_record', 'Extrait de casier judiciaire'), ('id_card', "Pièce d'identité"), ('other', 'Autre')], max_length=32, verbose_name='Type')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='N° document')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Date émission')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Date expiration')),
                ('file', models.FileField(blank=True, null=True, upload_to='drivers/documents/', verbose_name='Fichier')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.driver')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Document chauffeur',
                'verbose_name_plural': 'Documents chauffeurs',
                'db_table': 'fleet_driver_documents',
            },
        ),
        migrations.CreateModel(
            name='DriverHRNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Contenu')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('suspension', 'Suspension'), ('reactivation', 'Réactivation'), ('training', 'Formation'), ('warning', 'Avertissement'), ('other', 'Autre')], default='note', max_length=32, verbose_name='Nature')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_notes', to='fleet.driver')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Note RH chauffeur',
                'verbose_name_plural': 'Notes RH chauffeurs',
                'db_table': 'fleet_driver_hr_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
