# Generated by Django 5.2.18 on 2026-10-11 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_driver_hr_notes_and_documents'),
        ('voyage', '0008_seatmap_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='axles_count',
            field=models.PositiveIntegerField(blank=True, help_text='Pour blueprint SVG — 2 (bus standard) à 4 (double-pont)', null=True, verbose_name="Nombre d'essieux"),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='default_seat_map',
            field=models.ForeignKey(blank=True, help_text='Plan utilisé par défaut pour les véhicules créés avec ce type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_types_default', to='voyage.seatmap', verbose_name='Plan de sièges par défaut'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='wheelbase_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Distance axe avant / axe arrière, pour blueprint SVG', null=True, verbose_name='Empattement (mm)'),
        ),
    ]
