# Generated by Django 5.2.17 on 2026-08-25 02:22

import core.models
import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='Pays')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Coordonnées')),
                ('type', models.CharField(blank=True, choices=[('station', 'Gare routière'), ('depot', 'Dépôt'), ('hub', 'Hub logistique'), ('client_address', 'Adresse client'), ('other', 'Autre')], default='other', max_length=30, verbose_name='Type')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
                'db_table': 'geo_places',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('type', models.CharField(choices=[('service', 'Zone de service'), ('geofence', 'Géofence'), ('tariff', 'Zone tarifaire')], max_length=20, verbose_name='Type')),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326, verbose_name='Périmètre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('alert_on_exit', models.BooleanField(default=False, verbose_name='Alerte sortie')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'geo_zones',
            },
        ),
    ]
