# Generated by Django 5.2.17 on 2026-08-25 02:22

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('trip', 'Voyage'), ('order', 'Commande colis'), ('delivery_task', 'Tâche livraison'), ('parcel', 'Colis'), ('incident', 'Incident')], max_length=30, verbose_name="Type d'entité")),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_system', models.BooleanField(default=False, verbose_name='Système (non supprimable)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='iam.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'workflow_definitions',
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Couleur (hex)')),
                ('display_order', models.PositiveSmallIntegerField(verbose_name='Ordre affichage')),
                ('is_initial', models.BooleanField(default=False, verbose_name='État initial')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='État terminal')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.workflowdefinition')),
            ],
            options={
                'verbose_name': 'État workflow',
                'verbose_name_plural': 'États workflow',
                'db_table': 'workflow_states',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('manual', 'Manuel'), ('automatic', 'Automatique'), ('on_event', 'Sur événement'), ('on_condition', 'Sur condition')], default='manual', max_length=20, verbose_name='Déclencheur')),
                ('event_type', models.CharField(blank=True, max_length=50, verbose_name="Type d'événement")),
                ('guard', models.JSONField(blank=True, default=dict, verbose_name='Conditions')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Priorité')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_out', to='workflow.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_in', to='workflow.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflowdefinition')),
            ],
            options={
                'verbose_name': 'Transition',
                'verbose_name_plural': 'Transitions',
                'db_table': 'workflow_transitions',
            },
        ),
        migrations.CreateModel(
            name='WorkflowHook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hook_type', models.CharField(choices=[('notify', 'Notification'), ('update_field', 'Mise à jour champ'), ('webhook', 'Webhook'), ('celery_task', 'Tâche Celery')], max_length=20, verbose_name='Type')),
                ('config', models.JSONField(verbose_name='Configuration')),
                ('execution_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre exécution')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='workflow.workflowtransition')),
            ],
            options={
                'verbose_name': 'Hook',
                'verbose_name_plural': 'Hooks',
                'db_table': 'workflow_hooks',
                'ordering': ['execution_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'entity_type'), name='unique_active_workflow_per_tenant_entity'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('workflow', 'code'), name='unique_state_code_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('workflow', 'display_order'), name='unique_display_order_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(fields=('workflow', 'from_state', 'to_state'), name='unique_transition_per_workflow'),
        ),
    ]
