# Generated by Django 5.2.17 on 2026-08-26 23:39

import core.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_initial'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('type', models.CharField(choices=[('depot', 'Dépôt'), ('hub', 'Hub logistique'), ('client_site', 'Site client'), ('restricted', 'Zone restreinte'), ('country_border', 'Frontière')], max_length=20, verbose_name='Type')),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326, verbose_name='Périmètre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('alert_rules', models.JSONField(blank=True, default=dict, verbose_name="Règles d'alerte")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Géofence',
                'verbose_name_plural': 'Géofences',
                'db_table': 'tracking_geofences',
            },
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('enter', 'Entrée'), ('exit', 'Sortie'), ('dwell', 'Stationnement')], max_length=10, verbose_name='Type')),
                ('event_at', models.DateTimeField(verbose_name='Survenu à')),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.geofence')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Événement géofence',
                'verbose_name_plural': 'Événements géofence',
                'db_table': 'tracking_geofence_events',
                'ordering': ['-event_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32, unique=True, verbose_name='Token')),
                ('resource_type', models.CharField(choices=[('order', 'Commande colis'), ('trip', 'Voyage')], max_length=10, verbose_name='Type de ressource')),
                ('resource_id', models.UUIDField(verbose_name='ID ressource')),
                ('expires_at', models.DateTimeField(verbose_name='Expire à')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Lien de suivi',
                'verbose_name_plural': 'Liens de suivi',
                'db_table': 'tracking_links',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Position')),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Vitesse (km/h)')),
                ('heading', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Cap (azimut)')),
                ('accuracy_m', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Précision (m)')),
                ('altitude_m', models.SmallIntegerField(blank=True, null=True, verbose_name='Altitude (m)')),
                ('source', models.CharField(choices=[('traccar', 'Traccar'), ('driver_app', 'App chauffeur'), ('manual', 'Manuel')], default='driver_app', max_length=10, verbose_name='Source')),
                ('recorded_at', models.DateTimeField(db_index=True, verbose_name='Capturée à')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée à')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='fleet.driver')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='iam.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'tracking_positions',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['vehicle', '-recorded_at'], name='tracking_po_vehicle_a2e1cd_idx'), models.Index(fields=['tenant', '-recorded_at'], name='tracking_po_tenant__da6c86_idx')],
            },
        ),
    ]
