# Generated by Django 5.2.17 on 2026-08-26 23:39

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=10, verbose_name='Canal')),
                ('recipient', models.CharField(max_length=100, verbose_name='Destinataire')),
                ('event_type', models.CharField(max_length=50, verbose_name="Type d'événement")),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('status', models.CharField(choices=[('queued', 'En file'), ('sent', 'Envoyée'), ('delivered', 'Livrée'), ('failed', 'Échouée')], default='queued', max_length=20, verbose_name='Statut')),
                ('provider', models.CharField(blank=True, max_length=30, verbose_name='Provider')),
                ('provider_message_id', models.CharField(blank=True, max_length=100, verbose_name='ID message provider')),
                ('failure_reason', models.CharField(blank=True, max_length=300, verbose_name="Motif d'échec")),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée à')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livrée à')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de notification',
                'verbose_name_plural': 'Logs de notification',
                'db_table': 'notifications_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50, verbose_name="Type d'événement")),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push'), ('email', 'Email')], max_length=10, verbose_name='Canal')),
                ('language', models.CharField(default='fr', max_length=2, verbose_name='Langue')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Sujet')),
                ('template_body', models.TextField(verbose_name='Corps du message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Template de notification',
                'verbose_name_plural': 'Templates de notification',
                'db_table': 'notifications_templates',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'event_type', 'channel', 'language'), name='unique_template_per_tenant_event_channel_lang')],
            },
        ),
    ]
