# Generated by Django 5.2.17 on 2026-09-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('push', 'Push'), ('in_app', 'In-app / back-office'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10, verbose_name='Canal'),
        ),
    ]
