# Generated by Django 5.2.17 on 2026-09-06 01:33

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_add_notification_preferences'),
        ('notifications', '0003_rename_event_type_to_event_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='action_url_template',
            field=models.CharField(blank=True, help_text='CTA du message, rendu comme un gabarit Django.', max_length=500, verbose_name="URL d'action (gabarit)"),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_template',
            field=models.CharField(blank=True, help_text="Rendu pour le titre push (≤45 caractères après rendu), l'item in-app et le sujet e-mail.", max_length=200, verbose_name='Titre (gabarit)'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_code',
            field=models.CharField(max_length=100, verbose_name="Code d'événement"),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_code',
            field=models.CharField(db_index=True, max_length=100, verbose_name="Code d'événement"),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.models.UUIDv7Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_code', models.CharField(db_index=True, max_length=100, verbose_name="Code d'événement")),
                ('trigger_scope', models.CharField(choices=[('user', 'Utilisateur individuel'), ('role', 'Broadcast rôle'), ('tenant', 'Broadcast tenant')], max_length=10, verbose_name="Portée d'émission")),
                ('trigger_role', models.CharField(blank=True, help_text='Rôle destinataire si trigger_scope=role', max_length=20, verbose_name='Rôle visé')),
                ('priority', models.CharField(choices=[('critical', 'Critique'), ('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], max_length=10, verbose_name='Priorité')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Corps')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name="URL d'action")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lue à')),
                ('acked_at', models.DateTimeField(blank=True, help_text='Pour les événements avec requires_ack', null=True, verbose_name='Accusée à')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire à')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Calculée par le service (Ticket B) : {event_code}:{actor_id}:{target_hash}', max_length=100, verbose_name="Clé d'idempotence")),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(blank=True, help_text="Item de centre d'alertes associé, s'il y en a un. Reste vide pour les envois sans contrepartie in-app (OTP SMS, par exemple).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_attempts', to='notifications.notification', verbose_name='Notification'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'recipient_user', 'read_at'], name='notificatio_tenant__6cb627_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'event_code', 'created_at'], name='notificatio_tenant__78fabc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'idempotency_key'], name='notificatio_tenant__0f8a9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('tenant', 'recipient_user', 'idempotency_key'), name='unique_notification_idempotency_per_tenant_user'),
        ),
    ]
